Issue 100 enhancement add naive and top k methods for conformal classification
scikit-learn-contrib/MAPIE pull request #111
Opened 2021-11-19 13:58 UTC by vincentblot28

# Description

Add top_k and naive methods to classication

Fixes #101 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have read the [contributing guidelines](https://github.com/simai-ml/MAPIE/blob/master/CONTRIBUTING.rst)
- [x] I have updated the [HISTORY.rst](https://github.com/simai-ml/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/simai-ml/MAPIE/blob/master/AUTHORS.rst) files
- [x] Linting passes successfully : `make lint`
- [x] Typing passes successfully : `make type-check`
- [x] Unit tests pass successfully : `make tests`
- [x] Coverage is 100% : `make coverage`
- [x] Documentation builds successfully : `make doc`

2021-11-19 15:55 UTC, gmartinonQM requested changes
Good ! Juste un doute sur le calcul du conformity score

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +        - "naive", sum of the probabilities until the 1-alpha thresold.
Peut-on juste les classer de la plus simple à la plus compliquée dans la docstring stp ?

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +    valid_methods_ = ["score", "cumulated_score", "naive", "top_k"]
idem, classer de la plus simple à la plus compliquée

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +        elif self.method == "naive":
idem, tout mettre dans l'ordre simple vers compliqué dans l'ordre de lecture du code

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +        redicition sets may be different from the others.
typo: prediction

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +            )
Hum, ça me paraît magique comme ligne de code. Est-on vraiment sûr que ça donne le bon résultat ? Je pense avoir trouvé un contre-exemple 

```
y_pred_proba = np.array([[0.01, 0.5, 0.01, 0.3, 0.01, 0.1, 0.07], [0.5, 0.4, 0.01, 0.01, 0.01, 0.01, 0.06]])
y = np.array([3, 6])
index = np.fliplr(np.argsort(y_pred_proba, axis=1))
conformity_scores_ = np.take_along_axis(
                index,
                y.reshape(-1, 1),
                axis=1
            )
expected = np.array([1, 2]).reshape(-1, 1)
np.testing.assert_allclose(expected, conformity_scores_)

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +            index = np.fliplr(np.argsort(y_pred_proba, axis=1))
garder la convention `index_sorted` (ou changer la convention en `index` dans tout le module)

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +                    self.method == "naive"):
pas très beau ce saut de ligne, privilégier : 
```
elif self.method in ["naive", "cumulated_score"]:

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +                                EPSILON),
Pas très beau ce saut de ligne, privilégier : 
```
(
     y_pred_proba >= y_pred_proba_last[:, iq] - EPSILON
),
```
et enlever le `np.squeeze` à la ligne précédente (car le reshape et le squeeze sont inverses l'un de l'autre)

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +                                EPSILON),
Même chose ligne 688 d'ailleurs : on peut faire l'économie d'un `squeeze/reshape` successifs, peut-être avec un hstack ou un vstack, à voir

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +                        np.ma.masked_where(
Je pense que le masque est inutile ici, car ce n'est pas chaîné avec un `argmax` ou un `argmin`

2021-11-19 15:55 UTC, gmartinonQM commented on mapie/classification.py
> +                        np.ma.masked_where(
Idem ligne 698 d'ailleurs

2021-11-19 16:07 UTC, vincentblot28 commented on mapie/classification.py
> +        - "naive", sum of the probabilities until the 1-alpha thresold.
naive --> score --> cumulated_score --> top_k ?

2021-11-19 16:09 UTC, vincentblot28 commented on mapie/classification.py
> +        redicition sets may be different from the others.
done

2021-11-19 16:15 UTC, vtaquet commented on mapie/classification.py
> +        - "naive", sum of the probabilities until the 1-alpha thresold.
Oui ce classement me parait bien.

2021-11-19 17:08 UTC, vincentblot28 commented on mapie/classification.py
> +        - "naive", sum of the probabilities until the 1-alpha thresold.
done

2021-11-19 17:08 UTC, vincentblot28 commented on mapie/classification.py
> +    valid_methods_ = ["score", "cumulated_score", "naive", "top_k"]
done

2021-11-19 17:08 UTC, vincentblot28 commented on mapie/classification.py
> +        elif self.method == "naive":
done

2021-11-19 17:19 UTC, vincentblot28 commented on mapie/classification.py
> +            )
En effet ! ça marchait dans le cadre du pipeline de test mais ton cas est un contre exemple. Il faut ici prendre l' `argsort`de `index_sorted` pour avoir le résultat voulu

2021-11-19 17:20 UTC, vincentblot28 commented on mapie/classification.py
> +            index = np.fliplr(np.argsort(y_pred_proba, axis=1))
étant donné que l'on fait un `argsort` supplémentaire, faut l'appeler comme ceux qui n'ont pas ce `argsort`en plus ?

2021-11-19 17:21 UTC, vincentblot28 commented on mapie/classification.py
> +                    self.method == "naive"):
done

2021-11-19 17:33 UTC, vincentblot28 commented on mapie/classification.py
> +                                EPSILON),
Le np.queeze a été supprimé, par contre `y_pred_proba >= y_pred_proba_last[:, iq] - EPSILON` ne tient pas sur une ligne

2021-11-19 17:44 UTC, vincentblot28 commented on mapie/classification.py
> +                        np.ma.masked_where(
done

2021-11-19 17:44 UTC, vincentblot28 commented on mapie/classification.py
> +                                EPSILON),
résolu avec les modifications faites suite au commentaire suivant

2021-11-19 19:16 UTC, gmartinonQM commented on mapie/classification.py
> +            index = np.fliplr(np.argsort(y_pred_proba, axis=1))
OK admettons

2021-11-19 20:33 UTC, gmartinonQM approved these changes
Tout est bon ! Il manque juste le HISTORY.rst à remplir, peux-tu ajouter un bullet point avec tes méthodes naive et top-k ajoutée ? Peux-tu aussi ajouter les bullets points que Vianney a manqué (documentation et tutoriel de J+aB et APS ?

2021-11-19 20:33 UTC, gmartinonQM commented on mapie/classification.py
> +            )
Ce double argsort me fait des noeuds au cerveau, mais c'est bien la bonne solution !

2021-11-22 10:02 UTC, vtaquet commented
I had the same comments but the new commits took them into account. After a discussion with Vincent, I'm fine with the double `np.argsort` that solves what we want to do in `fit`. Good job Vincent !

2021-11-22 10:04 UTC, merged