change the warnings in cqr predictions
scikit-learn-contrib/MAPIE pull request #253
Opened 2023-01-10 15:39 UTC by tmorzade

# Description

Fixes a bug in two warnings in the MapieQuantileRegressor predictions

## Type of change

Please remove options that are irrelevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist

- [x] I have read the [contributing guidelines](https://github.com/simai-ml/MAPIE/blob/master/CONTRIBUTING.rst)
- [x] I have updated the [HISTORY.rst](https://github.com/simai-ml/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/simai-ml/MAPIE/blob/master/AUTHORS.rst) files
- [x] Linting passes successfully : `make lint`
- [x] Typing passes successfully : `make type-check`
- [x] Unit tests pass successfully : `make tests`
- [x] Coverage is 100% : `make coverage`
- [x] Documentation builds successfully : `make doc`

2023-01-11 13:05 UTC, vincentblot28 commented on mapie/utils.py
> +            + "the lower predictions at some points."
Upper quantile and lower quantile ?

2023-01-12 15:30 UTC, LacombeLouis approved these changes
This corrects the main issues pointed out: warning phrasing and the order of the element in lign 459. However, it does not fully satisfy some of the comments from @gmartinonQM with regard to a more explicit warning message.

2023-01-17 14:11 UTC, LacombeLouis requested changes

2023-01-17 14:11 UTC, LacombeLouis commented on mapie/quantile_regression.py
> +        y_preds = np.empty(
Not sure why we are making this change? Why do we want to set the values to 0 as oppose to `np.nan`?

2023-01-17 14:11 UTC, LacombeLouis commented on mapie/tests/test_utils.py
> +        sample_weight: Optional[ArrayLike]) -> None:
I believe this is the correct indentation?

def test_fit_estimator(
        estimator: Any,
        sample_weight: Optional[ArrayLike]
) -> None:

2023-01-17 14:11 UTC, LacombeLouis commented on mapie/utils.py
>  def check_alpha_and_n_samples(
I believe this is the correct indetation?

def check_alpha_and_n_samples(
        alphas: Union[Iterable[float], float],
        n: int
) -> None:

2023-01-19 09:44 UTC, LacombeLouis approved these changes

2023-01-19 11:30 UTC, merged