Update ts-changepoint-notebook
scikit-learn-contrib/MAPIE pull request #487
Opened 2024-07-19 15:10 UTC by BaptisteCalot

# Description

Resolution of several issues within the Notebook ts-changepoint :

- Reconstruction of the higher and lower quantiles, which were available as attributes of the MapieTimeSeriesRegressor() class in Mapie version 0.7 and were lost in version 0.8.

- Handling of infinite arrays when alpha is too small in the coverage calculation with the function regression_coverage_score().

- Addition of prediction interval calculations with adapt_conformal_inference for the aci method, modeled after what was developed in the notebook for the enbpi method

Fixes #475 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Add test_inf_values_with_warning_inf() in order to test check_array_inf with warning_inf=True

# Checklist

- [ ] I have read the [contributing guidelines](https://github.com/scikit-learn-contrib/MAPIE/blob/master/CONTRIBUTING.rst)
- [ ] I have updated the [HISTORY.rst](https://github.com/scikit-learn-contrib/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/scikit-learn-contrib/MAPIE/blob/master/AUTHORS.rst) files
- [ ] Linting passes successfully : `make lint`
- [ ] Typing passes successfully : `make type-check`
- [ ] Unit tests pass successfully : `make tests`
- [ ] Coverage is 100% : `make coverage`
- [ ] Documentation builds successfully : `make doc`

2024-07-22 09:35 UTC, vincentblot28 commented on mapie/metrics.py
> +        np.isinf(y_pred_low) | np.isinf(y_pred_up)
why doest this formula changes if we have infinite intervals ?

2024-07-22 14:40 UTC, LacombeLouis requested changes
Hey @BaptisteCalot, thank you for fixing the issue with this PR!
In this notebook we need to fix only the `lower_quantiles` and `higher_quantiles`. Additionally, we add the plot of this for the `ACI` method.

Could you make a couple changes to improve the notebook:
- Make a function to calculate the `lower_quantiles` and `higher_quantiles`

2024-07-25 09:06 UTC, LacombeLouis approved these changes

2024-07-26 07:42 UTC, LacombeLouis commented
Note that this test has not been needed:
- [ ] Add test_inf_values_with_warning_inf() in order to test check_array_inf with warning_inf=True
--> not needed and would be solved in a future PR see issue: #488.

2024-07-26 07:43 UTC, merged