Dev
scikit-learn-contrib/MAPIE pull request #86
Opened 2021-09-02 14:58 UTC by vtaquet

# Description

* Renaming estimators.py module to regression.py
* New classification.py module with MapieClassifier class, that estimate prediction sets from softmax score
* New set of unit tests for classification.py module
* Modification of the documentation architecture
* Split example gallery into separate regression and classification galleries
* Add first classification examples
* Add method classification_coverage_score in the module metrics.py

Fixes #(issue)

## Type of change

Please check options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Set of unit tests in `test_classification.py` et `test_utils.py`

# Checklist:

- [x] I have read the [contributing guidelines](https://github.com/simai-ml/MAPIE/blob/master/CONTRIBUTING.rst)
- [x] I have updated the [HISTORY.rst](https://github.com/simai-ml/MAPIE/blob/master/HISTORY.rst) and [AUTHORS.rst](https://github.com/simai-ml/MAPIE/blob/master/AUTHORS.rst) files
- [x] Linting passes successfully : `flake8 . --exclude=doc`
- [x] Typing passes successfully : `mypy mapie examples --strict`
- [x] Unit tests pass successfully : `pytest -vs --doctest-modules mapie`
- [x] Coverage is 100% : `pytest -vs --doctest-modules --cov-branch --cov=mapie --pyargs mapie`
- [x] Documentation builds successfully : `cd doc; make clean; make html`

2021-09-03 19:13 UTC, gmartinonQM requested changes
Good job !

On commence à se rendre compte qu'il y a beaucoup de copiés-collés entre classification et regression, notamment sur les checks et les tests unitaires. Grosse refacto en vue après cette MR

2021-09-03 19:13 UTC, gmartinonQM commented on mapie/tests/test_classification.py
> +    y_pred_float1, y_pis_float1 = mapie.predict(X_lr, alpha=alpha[0])
troquer `pis` par `ps` ou `pred_set`

2021-09-03 19:13 UTC, gmartinonQM commented on mapie/tests/test_classification.py
> +    _, y_pi_mapie = mapie.predict(X_toy, alpha=0.2)
troquer `y_pi_mapie` par `y_ps` ou `y_pred_set`

2021-09-03 19:13 UTC, gmartinonQM commented on examples/plot_toy_model.py
> -"""
Pourquoi le fichier examples/plot_toy_model.py a été supprimé ?

2021-09-03 19:13 UTC, gmartinonQM commented on mapie/tests/test_classification.py
> +    )
réindenter d'un cran à gauche

2021-09-03 19:13 UTC, gmartinonQM commented on mapie/tests/test_classification.py
> +    )
réindenter d'un cran à gauche

2021-09-06 14:37 UTC, vtaquet commented on README.rst
> +[2] Mauricio Sadinle, Jing Lei, \& Larry Wasserman.
Done

2021-09-06 14:40 UTC, vtaquet commented on doc/quick_start.rst
> +This package allows you to easily estimate prediction intervals (or prediction sets)
Je propose une petite modification à ton paragraphe:

This package allows you to easily estimate uncertainties in both regression and classification settings. In regression settings, MAPIE provides prediction intervals on single-output data. In classification settings, MAPIE provides prediction sets on multi-class data. In any case, MAPIE is compatible with any scikit-learn-compatible estimator.

2021-09-06 14:42 UTC, vtaquet commented on doc/theoretical_description_classification.rst
> +TO BE CONTINUED
Ajoutées

2021-09-06 14:42 UTC, vtaquet commented on doc/theoretical_description_regression.rst
> +The :class:`mapie.classification.MapieRegressor` class uses various
Corrigé

2021-09-06 14:43 UTC, vtaquet commented on doc/theoretical_description_regression.rst
> +resampling methods based on the jackknife strategy
Corrigé

2021-09-06 14:46 UTC, vtaquet commented on mapie/regression.py
> +from .utils import check_n_features_in, check_alpha
Corrigé

2021-09-06 14:49 UTC, vtaquet commented on mapie/tests/test_metrics.py
> +from mapie.metrics import classification_coverage_score
Corrigé

2021-09-06 14:51 UTC, vtaquet commented on mapie/tests/test_metrics.py
> +    [False,  True, False, False]
Corrigé

2021-09-06 14:54 UTC, vtaquet commented on mapie/utils.py
> +        Backend estimator of MAPIE.
Ajouté

2021-09-06 14:58 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +An example plot of :class:`mapie.classification.MapieClassifier`.
Je propose de supprimer momentanément cet exemple car il servira de tutoriel qu'Akim est en train de préparer.

2021-09-07 06:34 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +when the model is uncertain at the border between two labels. The null region
Modifié.

2021-09-07 06:35 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +
Supprimé

2021-09-07 06:37 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +When the class coverage is not large enough, the prediction sets can be empty
Modifié

2021-09-07 06:37 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +when the model is uncertain at the border between two labels. The null region
Modifié

2021-09-07 06:37 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +
Supprimé

2021-09-07 06:37 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +alphas = [0.2, 0.1, 0.05]
Corrigé

2021-09-07 06:41 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +for center, cov in zip(centers, covs):
Modifié

2021-09-07 06:43 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +y_train = np.stack([i for i in range(3) for _ in range(n_samples)]).ravel()
Modifié

2021-09-07 18:00 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +X_test = np.stack([
Pour garder le même format, j'ai fait un meshgrid suivi d'un stack.

2021-09-07 18:01 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +y_pred_mapie, y_pi_mapie = mapie.predict(X_test, alpha=alphas)
Modifié

2021-09-07 18:16 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +y_train_col = [colors[int(i)] for _, i in enumerate(y_train)]
Modifié

2021-09-07 18:26 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +covs = [[[1, 0], [0, 1]], [[2, 0], [0, 2]], [[5, 0], [0, 1]]]
Modifié

2021-09-07 18:35 UTC, vtaquet commented on mapie/metrics.py
> +    ... ])
J'ai ajouté des `True` à chaque ligne pour créer des prediction sets.

2021-09-07 18:36 UTC, vtaquet commented on mapie/metrics.py
> +    coverage = y_pred_set[np.arange(len(y_true)), y_true].mean()
Modifié

2021-09-07 18:41 UTC, vtaquet commented on mapie/tests/test_regression.py
>      np.testing.assert_allclose(coverage, COVERAGES["prefit"], rtol=1e-2)
Fonctions supprimées

2021-09-07 18:43 UTC, vtaquet commented on mapie/tests/test_utils.py
> +)
Ce jeu de données est utilisée dans la fonction `test_valid_shape_no_n_features_in`

2021-09-08 07:39 UTC, vtaquet commented on mapie/tests/test_utils.py
> +class DumbClassifier:
Modifié

2021-09-08 07:48 UTC, gmartinonQM commented on doc/quick_start.rst
> +This package allows you to easily estimate prediction intervals (or prediction sets)
OK !

2021-09-08 07:49 UTC, gmartinonQM commented on examples/classification/plot_blobs.py
> +An example plot of :class:`mapie.classification.MapieClassifier`.
OK !

2021-09-08 08:15 UTC, vtaquet commented on mapie/tests/test_metrics.py
> +    [False,  True, False, False]
J'ai rajouté quelques tests sur `classification_coverage_score` afin d'avoir les mêmes tests que `regression_coverage_score`.

2021-09-08 08:19 UTC, vtaquet commented on mapie/tests/test_utils.py
> +@pytest.mark.parametrize(
On peut garder cette paramètrisation en test `DumbEstimator` sur `X_reg` et `X_lr` (maintenant dénommé `X_classif`)

2021-09-08 08:20 UTC, vtaquet commented on mapie/tests/test_utils.py
> +@pytest.mark.parametrize("CV", ["prefit", None])
J'ai ajouté la variable `cv` dans la fonction de test

2021-09-08 08:20 UTC, vtaquet commented on mapie/tests/test_utils.py
> +    estimator = Estimator
Modifié

2021-09-08 08:24 UTC, vtaquet commented on mapie/classification.py
> +          By default "score".
Ajouté

2021-09-08 08:28 UTC, vtaquet commented on mapie/classification.py
> +          the distribution of scores.
Suprimés

2021-09-08 08:28 UTC, vtaquet commented on mapie/classification.py
> +        By default ``None``.
Modifié

2021-09-08 08:28 UTC, vtaquet commented on mapie/classification.py
> +from .utils import check_alpha_and_n_samples
Fusionné

2021-09-08 08:28 UTC, vtaquet commented on mapie/classification.py
> +from sklearn.model_selection import train_test_split
Supprimé

2021-09-08 08:29 UTC, vtaquet commented on mapie/classification.py
> +from sklearn.utils.multiclass import check_classification_targets
Remplacé

2021-09-08 08:29 UTC, vtaquet commented on mapie/classification.py
> +    random_state:  Optional[int]
Supprimé

2021-09-08 08:30 UTC, vtaquet commented on mapie/classification.py
> +        By default ``None``.
Ajouté

2021-09-08 08:30 UTC, vtaquet commented on mapie/classification.py
> +        By default ``0``.
Ajouté

2021-09-08 08:32 UTC, vtaquet commented on mapie/classification.py
> +    ----------
Ajouté

2021-09-08 08:43 UTC, vtaquet commented on mapie/classification.py
> +        Number of samples passed to the fit method.
Attribut propagé. En pratique, cet attribut devrait être une liste lorsqu'on fait de la validation croisée. J'anticipe donc le type en `Union[int, List[int]]`.

2021-09-08 08:43 UTC, vtaquet commented on mapie/classification.py
> +        random_state: Optional[int] = None,
Supprimé

2021-09-08 08:43 UTC, vtaquet commented on mapie/classification.py
> +        self.random_state = random_state
Supprimé

2021-09-08 08:44 UTC, vtaquet commented on mapie/classification.py
> +            raise ValueError(
Ce check a été supprimé

2021-09-08 08:45 UTC, vtaquet commented on mapie/classification.py
> +        cv: Optional[Union[float, str]] = None
J'anticipe la validation croisée en changeant le type en `Optional[Union[int, str, BaseCrossValidator]]`.

2021-09-08 08:45 UTC, vtaquet commented on mapie/classification.py
> +        float between 0 and 1.
Supprimé

2021-09-08 08:46 UTC, vtaquet commented on mapie/classification.py
> +            'prefit', None, or float between 0.0 and 1.0.
Supprimé

2021-09-08 08:46 UTC, vtaquet commented on mapie/classification.py
> +        cv : Optional[Union[float, str]], by default ``None``.
Modifié en `Optional[Union[int, str, BaseCrossValidator]], optional`

2021-09-08 08:47 UTC, vtaquet commented on mapie/classification.py
> +            return cv
Modifié

2021-09-08 08:48 UTC, vtaquet commented on mapie/classification.py
> +            return cv
Supprimé. On pourra déplacer cette fonction dans `utils.py` lorsque la validation croisée sera inclue car les checks seront similaires à `MapieRegressor`.

2021-09-08 08:48 UTC, vtaquet commented on mapie/classification.py
> +            "Allowed value is 'prefit' or float between 0.0 and 1.0."
Supprimé

2021-09-08 08:49 UTC, vtaquet commented on mapie/classification.py
> +        val_index: ArrayLike,
Argument rajouté.

2021-09-08 08:50 UTC, vtaquet commented on mapie/classification.py
> +            By default None.
Ajouté

2021-09-08 08:51 UTC, vtaquet commented on mapie/classification.py
> +        X_val, y_val = X[val_index], y[val_index]
Modifié

2021-09-08 08:52 UTC, vtaquet commented on mapie/classification.py
> +        return estimator, y_pred, X_val, y_val
Modifié

2021-09-08 08:52 UTC, vtaquet commented on mapie/classification.py
> +            By default None.
Ajouté

2021-09-08 08:53 UTC, vtaquet commented on mapie/classification.py
> +            X, y, force_all_finite=False, dtype=["float64", "int", "object"]
Ajouté

2021-09-08 08:53 UTC, vtaquet commented on mapie/classification.py
> +        check_classification_targets(y)
Remplacé

2021-09-08 08:55 UTC, vtaquet commented on mapie/classification.py
> +            )
Modifié

2021-09-08 08:56 UTC, vtaquet commented on mapie/classification.py
> +            X_val, y_val = X, y
Supprimé

2021-09-08 08:56 UTC, vtaquet commented on mapie/classification.py
> +        self.scores_ = 1 - y_pred[np.arange(len(y_pred)), y_val]
Modifié

2021-09-08 08:57 UTC, vtaquet commented on mapie/classification.py
> +        (n_samples,) and (n_samples, n_labels, n_alpha) if alpha is not None.
Oui bien vu, on ne fait pas du multi-label ici.

2021-09-08 08:58 UTC, vtaquet commented on mapie/classification.py
> +                "n_samples_val_",
Propagé

2021-09-08 09:01 UTC, vtaquet commented on mapie/classification.py
> +        y_pred = self.single_estimator_.predict(X)
Ajouté

2021-09-08 09:01 UTC, vtaquet commented on mapie/classification.py
> +                self.single_estimator_.predict_proba(X) > (1 - quantile)
Oui bien vu

2021-09-08 09:01 UTC, vtaquet commented on mapie/classification.py
> +            check_alpha_and_n_samples(alpha_, n)
Propagé

2021-09-08 09:21 UTC, gmartinonQM commented on mapie/tests/test_utils.py
> +@pytest.mark.parametrize(
OK

2021-09-08 09:22 UTC, gmartinonQM commented on mapie/tests/test_utils.py
> +)
OK

2021-09-08 14:14 UTC, vtaquet commented on mapie/classification.py
> +                    ((n + 1) * (1 - _alpha)) / n,
C'est vrai que c'est plus logique mathématiquement, et on obtient a priori les mêmes résultats avec `interpolation="lower"` .

2021-09-08 14:39 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    "score": Params(method="score", cv=None, random_state=1)
Modifié

2021-09-08 14:40 UTC, vtaquet commented on mapie/tests/test_classification.py
> +y_toy = np.stack([0, 0, 1, 0, 1, 2, 1, 2, 2])
Modifié

2021-09-08 14:40 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    )
Modifié

2021-09-08 14:40 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    assert mapie.cv is None
Modifié

2021-09-08 14:40 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    assert mapie.random_state is None
Supprimé

2021-09-08 14:41 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:41 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:41 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.predict(X_lr)
Modifié

2021-09-08 14:42 UTC, vtaquet commented on mapie/tests/test_classification.py
> +
Ajouté

2021-09-08 14:42 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:42 UTC, vtaquet commented on mapie/tests/test_classification.py
> +                            **STRATEGIES[strategy])
Modifié

2021-09-08 14:43 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:43 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    estimator.fit(X_lr, y_lr)
Modifié

2021-09-08 14:44 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:45 UTC, vtaquet commented on mapie/tests/test_classification.py
> +def test_valid_prefit_estimator_shape_no_n_features_in() -> None:
Supprimé

2021-09-08 14:46 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie_single.fit(X_lr, y_lr)
Modifié

2021-09-08 14:47 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    y_pred_multi = mapie_multi.predict(X_lr)
Ajouté

2021-09-08 14:47 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    n_samples = 500
Modifié

2021-09-08 14:49 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie1.fit(X_lr, y_lr, sample_weight=np.ones(shape=n_samples))
Modifié

2021-09-08 14:50 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    y_pred1 = mapie1.predict(X_lr)
Ajouté

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +def test_invalid_random_state(random_state: Any) -> None:
Supprimé

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 14:51 UTC, vtaquet commented on mapie/tests/test_classification.py
> +@pytest.mark.parametrize("cv", [None, "prefit", 0.2, 0.3])
Modifié

2021-09-08 14:53 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        mapie.fit(X_cal, y_cal)
Modifié

2021-09-08 14:54 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    y_pred, y_pis = mapie.predict(X, alpha=alpha)
Modifié

2021-09-08 15:01 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    assert y_pis.shape == (X.shape[0], 4, n_alpha)
Ajouté

2021-09-08 15:02 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    assert y_pred.shape == (X.shape[0],)
Ajouté

2021-09-08 15:04 UTC, vtaquet commented on mapie/tests/test_classification.py
> +    _, y_pi_mapie = mapie.predict(X_toy, alpha=0.2)
Modifié

2021-09-08 15:13 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        mapie.fit(X_lr, y_lr)
Modifié

2021-09-08 16:15 UTC, vtaquet commented on examples/plot_toy_model.py
> -"""
Ah oui bizarre, je le rajoute !

2021-09-08 16:16 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +])
L'exemple est supprimé pour le moment.

2021-09-08 16:16 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +y_pred_mapie, y_pi_mapie = mapie.predict(X_test, alpha=0.01)
L'exemple est supprimé pour le moment.

2021-09-08 16:16 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +y_train_col = [colors[i] for _, i in enumerate(y_train)]
L'exemple est supprimé pour le moment.

2021-09-08 16:17 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +y_pred_col = [colors[i] for _, i in enumerate(y_pred)]
L'exemple est supprimé pour le moment.

2021-09-08 16:17 UTC, vtaquet commented on examples/classification/plot_blobs.py
> +
L'exemple est supprimé pour le moment.

2021-09-08 16:25 UTC, gmartinonQM commented on mapie/classification.py
> +                    ((n + 1) * (1 - _alpha)) / n,
OK

2021-09-09 07:33 UTC, vtaquet commented on mapie/tests/test_classification.py
> +def test_invalid_prefit_estimator_shape() -> None:
C'est fait !

2021-09-09 09:03 UTC, gmartinonQM requested changes

2021-09-09 09:03 UTC, gmartinonQM commented on mapie/tests/test_regression.py
> +    y_pred_multi, y_pis_multi = mapie_multi.predict(X_toy, alpha=0.2)
pourquoi avoir changé ces valeurs de alpha ?

2021-09-09 09:03 UTC, gmartinonQM commented on mapie/tests/test_utils.py
> +)
Pas sûr que cette paramétrisation sur X,y soit nécessaire, car DumbEstimator est indépendant de X et y justement

2021-09-09 09:45 UTC, vtaquet commented on examples/classification/plot_sadinle2019_example.py
> +When the class coverage is not large enough, the prediction sets can be empty.
Ajouté

2021-09-09 09:45 UTC, vtaquet commented on mapie/classification.py
> +            return LogisticRegression(multi_class="multinomial").fit(X, y)
Exactement ! Une fois la CV implémentée, on pourra revenir en arrière.

2021-09-09 09:51 UTC, vtaquet commented on mapie/regression.py
> +    >>> y_pred, y_pis = pireg.predict(X_toy, alpha=0.5)
Avec `alpha = 0.1`, le `check_alpha_and_n_samples` effectué maintenant dans `MapieRegressor` envoie un message d'erreur.

2021-09-09 09:52 UTC, vtaquet commented on mapie/tests/test_classification.py
> +        np.array([0.2, 0.8]),
Voir commentaire précédent.

2021-09-09 09:52 UTC, vtaquet commented on mapie/tests/test_regression.py
> +    y_pred_multi, y_pis_multi = mapie_multi.predict(X_toy, alpha=0.2)
Voir commentaire précédent.

2021-09-09 09:55 UTC, vtaquet commented on mapie/tests/test_utils.py
> +)
En effet, j'ai simplifié la fonction.

2021-09-09 14:17 UTC, merged